---
layout: post
author: LIU,HONGYANG
tags: [Scala]
---





本文探讨Scala的异常处理，



首先，异常处理分为两类，一类是捕获异常，一类是抛出异常

抛出异常就是说，抛出一个异常参数，但是需要注意的是，抛出异常需要打印出信息。



捕获异常，如果无法捕获，就会到调用处。





```scala
package com.baishan.scala.demo54


class ExceptionExample2{
    def validate(age:Int)={
        if(age<18)
            throw new Exception("You are not eligible")
    }

    println("continue")
}

object demo54 {
    def main(args: Array[String]) {
        var e = new ExceptionExample2()
        e.validate(10)
    }
}
```



抛出异常继续执行

```
objc[5313]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin/java (0x1061704c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1061ea4e0). One of the two will be used. Which one is undefined.
continue
Exception in thread "main" java.lang.Exception: You are not eligible
	at com.baishan.scala.demo54.ExceptionExample2.validate(demo54.scala:7)
	at com.baishan.scala.demo54.demo54$.main(demo54.scala:16)
	at com.baishan.scala.demo54.demo54.main(demo54.scala)
```





其中@throws(classOf[Exception])是声明异常，就是抛出异常





https://blog.csdn.net/qq_26442553/article/details/108467307





https://blog.csdn.net/love284969214/article/details/82731776



```
 @throws(classOf[Exception])
  def uploadFile(uploadUrl: String, uploadFileName: String, localfileDirectory: String): Unit = {
    var response: HttpResponse[String] = _
    try {
      response = Http(uploadUrl).
        put(Source.fromFile(uploadFileName).getLines.toString).asString
    } catch {
      case ex: Exception => ex.printStackTrace()
    }

    if (response.is3xx || response.is4xx || response.is5xx) {
      throw new Exception("error")
    }
  }
```

对于异常而言，如果判断逻辑在try里面， 那么就会被捕获，被捕获就无法上传到上层逻辑，因此，应该抛出异常给上层逻辑。



https://dreamhomes.top/posts/202005241921.html